/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guild_manager;

import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author Mattheus
 */
public class UserInterface extends javax.swing.JFrame {
    private UserInterfaceController controller;
    
    /**
     * Creates new form Guild
     */
    public UserInterface() {
        controller = new UserInterfaceController(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabelJogador = new javax.swing.JLabel();
        jTextFieldJogador = new javax.swing.JTextField();
        jLabelPersonagem = new javax.swing.JLabel();
        jTextFieldPersonagem = new javax.swing.JTextField();
        jLabelRaca = new javax.swing.JLabel();
        jLabelClasse = new javax.swing.JLabel();
        jLabelLevel = new javax.swing.JLabel();
        jSpinnerLevel = new javax.swing.JSpinner();
        jLabelProfissao = new javax.swing.JLabel();
        jLabelDias = new javax.swing.JLabel();
        jCheckBoxDomingo = new javax.swing.JCheckBox();
        jCheckBoxSegunda = new javax.swing.JCheckBox();
        jCheckBoxTerca = new javax.swing.JCheckBox();
        jCheckBoxQuarta = new javax.swing.JCheckBox();
        jCheckBoxQuinta = new javax.swing.JCheckBox();
        jCheckBoxSexta = new javax.swing.JCheckBox();
        jCheckBoxSabado = new javax.swing.JCheckBox();
        jLabelHorario = new javax.swing.JLabel();
        jTextFieldHorario = new javax.swing.JTextField();
        jComboBoxProfissao = new javax.swing.JComboBox();
        jLabelLvlProfissao = new javax.swing.JLabel();
        jButtonSalvarDados = new javax.swing.JButton();
        jSpinnerLvlProfissao = new javax.swing.JSpinner();
        jLabelEspecialidade = new javax.swing.JLabel();
        jComboBoxEspecialidade = new javax.swing.JComboBox();
        jComboBoxRaca = new javax.swing.JComboBox();
        jComboBoxClasse = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxQuantPersonagem = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerQuantTank = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerQuantHealer = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerQuantRdps = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerQuantMdps = new javax.swing.JSpinner();
        jButtonCriarGrupo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelJogador.setText("Jogador:");

        jTextFieldJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJogadorActionPerformed(evt);
            }
        });

        jLabelPersonagem.setText("Personagem:");

        jLabelRaca.setText("Raca:");

        jLabelClasse.setText("Classe:");

        jLabelLevel.setText("Level:");

        jLabelProfissao.setText("Profissão:");

        jLabelDias.setText("Dias disponíveis");

        jCheckBoxDomingo.setText("Domingo");

        jCheckBoxSegunda.setText("Segunda");

        jCheckBoxTerca.setText("Terça");

        jCheckBoxQuarta.setText("Quarta");

        jCheckBoxQuinta.setText("Quinta");
        jCheckBoxQuinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxQuintaActionPerformed(evt);
            }
        });

        jCheckBoxSexta.setText("Sexta");

        jCheckBoxSabado.setText("Sábado");

        jLabelHorario.setText("Horário disponível:");

        jTextFieldHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHorarioActionPerformed(evt);
            }
        });

        jComboBoxProfissao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alchemy", "Engineering", "Tailoring" }));

        jLabelLvlProfissao.setText("Lvl da Profissão:");

        jButtonSalvarDados.setText("Salvar");
        jButtonSalvarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarDadosActionPerformed(evt);
            }
        });

        jLabelEspecialidade.setText("Especialidade:");

        jComboBoxEspecialidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tank", "Healer", "Rdps", "Mdps" }));

        jComboBoxRaca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "Worgen", "Troll", "Orc" }));

        jComboBoxClasse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hunter", "Mage", "Warlock", "Warrior" }));

        jLabel2.setText("Grupos");

        jLabel3.setText("Número de personagens:");

        jComboBoxQuantPersonagem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "10", "25" }));

        jLabel4.setText("Tank:");

        jLabel5.setText("Healer:");

        jLabel6.setText("Rdps:");

        jLabel7.setText("Mdps:");

        jButtonCriarGrupo.setText("Criar grupo");
        jButtonCriarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxQuantPersonagem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelJogador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPersonagem)
                                    .addComponent(jLabelLvlProfissao)
                                    .addComponent(jLabelLevel)
                                    .addComponent(jLabelClasse)
                                    .addComponent(jLabelRaca)
                                    .addComponent(jLabelProfissao)
                                    .addComponent(jLabelEspecialidade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPersonagem, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxRaca, javax.swing.GroupLayout.Alignment.TRAILING, 0, 148, Short.MAX_VALUE)
                            .addComponent(jComboBoxClasse, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerLevel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxProfissao, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxEspecialidade, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerLvlProfissao)
                            .addComponent(jTextFieldJogador))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxDomingo)
                                    .addComponent(jCheckBoxTerca)
                                    .addComponent(jCheckBoxQuinta))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxSexta)
                                    .addComponent(jCheckBoxQuarta)
                                    .addComponent(jCheckBoxSegunda)))
                            .addComponent(jCheckBoxSabado)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonSalvarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelHorario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelDias)
                        .addGap(64, 64, 64))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCriarGrupo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSpinnerQuantTank, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addComponent(jSpinnerQuantHealer)
                                .addComponent(jSpinnerQuantRdps)
                                .addComponent(jSpinnerQuantMdps)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDias)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJogador)
                    .addComponent(jTextFieldJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxDomingo)
                    .addComponent(jCheckBoxSegunda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPersonagem)
                    .addComponent(jTextFieldPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxTerca)
                    .addComponent(jCheckBoxQuarta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelRaca)
                        .addComponent(jComboBoxRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBoxQuinta)
                        .addComponent(jCheckBoxSexta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelClasse)
                        .addComponent(jComboBoxClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBoxSabado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelHorario)
                        .addComponent(jTextFieldHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProfissao)
                    .addComponent(jComboBoxProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinnerLvlProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabelLvlProfissao, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEspecialidade)
                            .addComponent(jComboBoxEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButtonSalvarDados)))
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxQuantPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerQuantTank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jSpinnerQuantHealer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jSpinnerQuantRdps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jSpinnerQuantMdps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCriarGrupo)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJogadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJogadorActionPerformed

    private void jCheckBoxQuintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxQuintaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxQuintaActionPerformed

    private void jTextFieldHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHorarioActionPerformed

    private void jButtonSalvarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarDadosActionPerformed
        // TODO add your handling code here:
        controller.dadosPersonagem();
    }//GEN-LAST:event_jButtonSalvarDadosActionPerformed

    private void jButtonCriarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarGrupoActionPerformed
        // TODO add your handling code here:
        controller.criarGrupo();
    }//GEN-LAST:event_jButtonCriarGrupoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCriarGrupo;
    private javax.swing.JButton jButtonSalvarDados;
    private javax.swing.JCheckBox jCheckBoxDomingo;
    private javax.swing.JCheckBox jCheckBoxQuarta;
    private javax.swing.JCheckBox jCheckBoxQuinta;
    private javax.swing.JCheckBox jCheckBoxSabado;
    private javax.swing.JCheckBox jCheckBoxSegunda;
    private javax.swing.JCheckBox jCheckBoxSexta;
    private javax.swing.JCheckBox jCheckBoxTerca;
    private javax.swing.JComboBox jComboBoxClasse;
    private javax.swing.JComboBox jComboBoxEspecialidade;
    private javax.swing.JComboBox jComboBoxProfissao;
    private javax.swing.JComboBox jComboBoxQuantPersonagem;
    private javax.swing.JComboBox jComboBoxRaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelClasse;
    private javax.swing.JLabel jLabelDias;
    private javax.swing.JLabel jLabelEspecialidade;
    private javax.swing.JLabel jLabelHorario;
    private javax.swing.JLabel jLabelJogador;
    private javax.swing.JLabel jLabelLevel;
    private javax.swing.JLabel jLabelLvlProfissao;
    private javax.swing.JLabel jLabelPersonagem;
    private javax.swing.JLabel jLabelProfissao;
    private javax.swing.JLabel jLabelRaca;
    private javax.swing.JSpinner jSpinnerLevel;
    private javax.swing.JSpinner jSpinnerLvlProfissao;
    private javax.swing.JSpinner jSpinnerQuantHealer;
    private javax.swing.JSpinner jSpinnerQuantMdps;
    private javax.swing.JSpinner jSpinnerQuantRdps;
    private javax.swing.JSpinner jSpinnerQuantTank;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextFieldHorario;
    private javax.swing.JTextField jTextFieldJogador;
    private javax.swing.JTextField jTextFieldPersonagem;
    // End of variables declaration//GEN-END:variables

    public String getTextFieldJogador() {
        return this.jTextFieldJogador.getText();
    }
    
    public String getTextFieldPersonagem() {
        return this.jTextFieldPersonagem.getText();
    }
    
    public JComboBox getComboBoxRaca(){
        return this.jComboBoxRaca;
    }
    
    public JComboBox getComboBoxClasse(){
        return this.jComboBoxClasse;
    }
    
    //JSpinner
    public JSpinner getSpinnerLevel(){
        return this.jSpinnerLevel;
    }
    
    public JComboBox getComboBoxProfissao(){
        return this.jComboBoxProfissao;
    }
    
    public JSpinner getSpinnerLvlProfissao(){
        return this.jSpinnerLvlProfissao;
    }
    
    public JComboBox getComboBoxEspecialidade(){
        return this.jComboBoxEspecialidade;
    }
    
    public JCheckBox getCheckBoxDomingo(){
        return this.jCheckBoxDomingo;
    }
    
    public JCheckBox getCheckBoxSegunda(){
        return this.jCheckBoxSegunda;
    }
    
    public JCheckBox getCheckBoxTerca(){
        return this.jCheckBoxTerca;
    }
    
    public JCheckBox getCheckBoxQuarta(){
        return this.jCheckBoxQuarta;
    }
    
    public JCheckBox getCheckBoxQuinta(){
        return this.jCheckBoxQuinta;
    }
    
    public JCheckBox getCheckBoxSexta(){
        return this.jCheckBoxSexta;
    }
    
    public JCheckBox getCheckBoxSabado(){
        return this.jCheckBoxSabado;
    }
    
    public String getTextFieldHorario() {
        return this.jTextFieldHorario.getText();
    }
    
    public JComboBox getQuantPersonagem(){
        return this.jComboBoxQuantPersonagem;
    }
    
    public JSpinner getSpinnerQuantTank(){
        return this.jSpinnerQuantTank;
    }
    
    public JSpinner getSpinnerQuantHealer(){
        return this.jSpinnerQuantHealer;
    }
    
    public JSpinner getSpinnerQuantRdps(){
        return this.jSpinnerQuantRdps;
    }
    
    public JSpinner getSpinnerQuantMdps(){
        return this.jSpinnerQuantMdps;
    }
    
}
